TestMVCApp/Models/OrderViewModel.cs
namespace TestMVCApp.Models
{
    public class OrderViewModel
    {
        
    }
}

TestMVCApp/Components/CartDetailViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using TestMVCApp.libs.Application;

namespace TestMVCApp.Components
{
   
    public class CartDetailViewComponent: ViewComponent
    {
        private readonly ICartService _cartService;

        public CartDetailViewComponent(ICartService cartService)
        {
            _cartService = cartService;
        }

        
        public async Task<IViewComponentResult> InvokeAsync() 
        {

            var cart = _cartService.GetCart();

            // cartsessiondan gelen data view bu vievcomponent içerisinde çeklip gönderilecek.
            // yani bu view component Shared/Components/CartDetail.cshtml dosyasına cart modelini taşıyacak. oraya yönlenicek

            return await Task.FromResult(View(cart));
        }

    }
}

TestMVCApp/Controllers/OrderController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TestMVCApp.libs.Application;
using TestMVCApp.libs.Data.Contexts;
using TestMVCApp.libs.Data.Repositories;
using TestMVCApp.libs.Domain;
using TestMVCApp.Models;

namespace TestMVCApp.Controllers
{


    // uygulama içerisindeki bir durumun saklama şekillerine biz state management ismini durum yönetimiş ismini vberiyor

    // State Management 2 ye ayrılır

    // 1. ServerSide => Session, Application, Cache => Sunucu yani deploy çıktımızı Hosting makinadaki çözümler
    // 2. ClientSide => QueryString, Hidden Input, Cookie, WebStorage vs.. Tarayıcı tarafındaki çözümler

    // QueryString => sayfalar araası veri taşıma işlemlerinde, sayfada bir search sonucu bir kayıt araması yaparken tercih edilir.

    // Örnek => www.sanalticaret.com/ürünler?marka=adidas&beden=42
    // marka ve beden => key iken
    // adidas ve 42 değerleri ise value dur.

    // Hidden Input => bazen form bilgilerini suncuuya gönderirken bazı alanları input type="hidden" ile son kullanıcıya göstermeden göndermemiz gerekebilir. mesela edit yaparken id alanın bir önceki dersimizde hidden input ile httpost methoduna taşımıştık.

    // Cookie => Kullanıcı Login olduktan sonraki kullanıcı adı ve Profil fotoğrafı gibi bilgileri her istek de sunucundan tekrar tekrar sorgulamak bir maliyet ve performans kaybıdır. bu sebep ile bu tarz bilgiler key value formatında string olarak cookie de saklanır. tarayıcnın veri saklamak için kullandığı bir alandır. Maksimum 4kb veri saklanabilir. Cookie deki bilgiler, suncuya istek altığında gerekirse HttpRequest içerisinden otomatik olarak taşınır. Hassas bilgiler için güvenli bir veri taşıma yöntemi değildir. Javascript ile cookie bilgisi okunarak ekranda bir şeyler gösterilebilir. 

    // Web Storage yönteminde ise cookieden farklı olarak tarayıcıdaki storage alanında session yani oturum bazlı yada persist yani kalıcı olarak key value cinsinden veri saklayabiliriz. Her bir httpRequest de bu veriler tarayıcıdan sunucuya taşınmaz. Bu sebep ile cookieden farklı olup daha güvenli bir yöntemdir. (LocalStorage, SessionStorage) 2 adet storage tekniğini tarayıcılar destekler. Javascript ile bu verileri manüpüle edebiliyoruz.

    // Server Side statelerimiz ise Session => Client tarayıcıyı açıp ilgili domain adresine bir web request de bulunduğu an sunucu tarafında bu web request için tanımlanmış unique bir id'dir. biz buna sunucu tarafında session diyoruz. Bu unique id client tarayıcı kapatmayana kadar sunucu tarafında değişmez. Ne zaman tarayıcıyı kapatır yada (gizli sekmeden) bir tab açarız bu durumda sunucu tarafında yeni bir sessionıd oluşur. Session Id oturum bazlı en güvenilir veri tutma yönetmidir. çünkü session daki bilgiler web request içerinde saklanmaz sunucu tarafında tutulur. Session hacklenmesi için sessionId değerinin client a taşınması gerekir ki, hacker server'a eriştikten sonra ilgili sessionId üzerinden sunucudaki session ait bilgileri çalsın. Sepet gibi hassas bilgiler, kart bilgileri vs session üzerinde tutulabilir. Yada oturum açan kullanıcıya ait özlük bilgileri her seferinde db den çekilmek yerine sessionda saklanabilir.

    // Application ise => Uygulama bazlı sunucu tarafında veri tutmamızı sağlayan bir yöntemdir. Application ile sitemizi ziyaret eden aktif kullanıcı sayısı, uygulama ile alaklı ayarlar (mail atmak için gerekli olan konfigürasyon bilgileri) vb durumlar için tercih edilir. Oturum ve kullanıcı bazlı herhangi bir bilgi saklamak doğru değildir. Bu web sayfamızın gün içerisinde kaç web request aldığını filan bulabiliriz. 



    // Cache => Yani verilerin sürekli veri kaynağından çekmek yerine bir başka kaynak belli bir süre tutulup, buradan daha hızlı okunması işlemi. Genelde gün içerisinde çok fazla değişim göstemeyecek, günde 1 kez güncellenen veri operasyonları için tercih edilen bir yöntemdir. 
    // Veri tabanındaki ürün kategorileri, web uygulamamıza ait menüler, web sitemize ait renk temaları ve renk kodları, uygulamaya ait bazı konfigürasyon değerleri vs cache üzerinden okunabilir. Cacheden okunan değerler bir sunucunun raminde belli bir müddet tutulduğu için diskten yani hardiskten yada bir databaseden okumadan çok daha performanslıdır. 


    // EF Core Identity Service => CookieAuthentication (FormsAuthentication) => Web Project tercihi
    // Api TokenBasedAuthentication => Access Token erişim bileti ile kimlik dpoğrulama
    // Windows => LDAP Windows Autentication => PC hesabı ile kimlik doğrulama
    // School and Coperation Account ile Authentication => sadece şirket kimlik doğrulama

    // External Authentication => FB, Twitter, Google vs üzerinden kimlik doğrulama

    // EF Core Identity ile yukarıdaki tüm kimilk dopğrulama yöntemlerini kullanabiliyoruz. bunun için hazır yapılar var ve hazır tablolar var









    public class OrderController : Controller
    {

        private ICartService _cartService;
        private IOrderService _orderService;

        private ICustomerRepository _custormerRepo;

        private readonly UserManager<IdentityUser> _userManager;

        public OrderController(
        ICartService cartService,
        IOrderService orderService,
        UserManager<IdentityUser> userManager,
        ICustomerRepository customerRepo

        )
        {


            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
            _custormerRepo = customerRepo;
        }

        // Product/Save
        // Sepeti tamamlama işleminde yada satın alma işleminde OrderService ile çalışmamız lazım.

        // JsonResult ile sayfa yenilenmeden AJAx ile data işlemleri yapabiliriz. Sepete ekleme işleminde sayfa yenilenmeden bu işlemi yapmış olduk


        [HttpGet]
        public async Task<ActionResult> DoOrder()
        {

            // sipariş formu açılısında kullanıcı oturum açmış ise bu durumda şuan oturum açan müşteri bilgilerini getir.
            if (User.Identity.IsAuthenticated)
            {
                var authenticatedUser = await _userManager.FindByNameAsync(User.Identity.Name);

                var customer = _custormerRepo.Find(authenticatedUser.Id);

                var model = new OrderInputModel();
                model.CustomerDetail = new CustomerDetailModel
                {
                    FullName = customer.FullName,
                    ShipAddress = customer.DefaultShippingAddress,
                    CustomerId = customer.Id,
                    PhoneNumber = customer.PhoneNumber
                };


                return View(model);

            }


            return View();
        }


        [HttpPost]
        public ActionResult DoOrder(OrderInputModel model)
        {
            // 1 sipariş düzgün bir şekilde oluşur ise bu bilgileri database gönderip siparişe çevireceğiz ve 
            // daha sonrasında kullanıcıya bir mesaj verip sms email filan göndereceğiz.

            // Kredi kartı işlem enum
            // Başarılı 200
            // red 300
            // Limit Yertersiz 500 gibi
            // eğer Başarılı ise Sipariş oluşturma işlemini yapıp kullanıcıya sipariş kodunu dönelim.


            // 2 kredi kartı doğrulmasını yalancıktan yapalım eğer limit yeterli ise ve red verilmediyse sipariş oluşsun ve kullanıcıya ViewBag ile sipariş kodunu göster


            if (ModelState.IsValid)
            {

                var cart = _cartService.GetCart();
                _orderService.DoOrder(cart, model);

                ViewBag.OrderCode = _orderService.orderCode;
                ViewBag.OrderStatus = _orderService.Status;

                return View();

            }


            ViewBag.OrderCode = string.Empty;
            ViewBag.OrderStatus = string.Empty;




            return View();
        }


    }
}

TestMVCApp/Views/Order/DoOrder.cshtml
@{
    ViewData["Title"] = "Satın Al";
}



@model OrderInputModel




<div class="container-fluid">


    <div class="row">
        @ViewBag.OrderStatus
        @ViewBag.OrderCode
    </div>

    <div class="row">

        <div class="col-8">
            <h2>Sipariş Formu</h2>
            <form method="POST" action="DoOrder">


                <div class="text-danger" asp-validation-summary="All"></div>


                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#customerStep">Müşteri Bilgileri</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#creditStep"> Kredi Kartı </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#orderStep"> Sipariş Ver </a>
                    </li>
                </ul>


                <div class="tab-content mt-5">
                    <div class="tab-pane container active" id="customerStep">


                        <input type="hidden" asp-for="CustomerDetail.CustomerId">

                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <input class="form-control" asp-for="CustomerDetail.FullName"
                                        placeholder="Müşteri Adsoyad" type="text" />
                                </div>

                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <input id="phoneNumber" class="form-control" asp-for="CustomerDetail.PhoneNumber"
                                        placeholder="Telefon" />
                                </div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col">

                                <div class="form-group">
                                    <textarea class="form-control" asp-for="CustomerDetail.ShipAddress" rows="5"
                                        cols="10" placeholder="Sipariş Adresi"></textarea>
                                </div>


                            </div>
                        </div>

                        <div class="row  float-right mr-2">

                            <button class="btn btn-primary" onclick="GotoNext('creditStep')"> Next >> </button>
                        </div>

                    </div>
                    <div class="tab-pane container fade" id="creditStep">

                        <div class="row">
                            <div class="col">



                                <div class="form-group">
                                    <input class="form-control" asp-for="CreditDetail.CardUser"
                                        placeholder="Kredi Kartı Sahibi"></textarea>
                                </div>


                            </div>
                        </div>

                        <div class="row">
                            <div class="col">



                                <div class="form-group">
                                    <input id="creditNumber" class="form-control" asp-for="CreditDetail.Credit"
                                        placeholder="Kart Numarası"></textarea>
                                </div>


                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <input id="validThru" class="form-control" asp-for="CreditDetail.ValidThru"
                                        placeholder="Son Kullanama Tarihi" />
                                </div>

                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <input id="cvv" id="phoneNumber" class="form-control" asp-for="CreditDetail.CVV"
                                        placeholder="Güvenlik Kodu" />
                                </div>

                            </div>
                        </div>


                        <div class="row  float-right mr-2">
                            <button class="btn btn-secondary" onclick="GotoPrev('customerStep')"> Prev << </button>
                                    &nbsp;
                                    <button class="btn btn-primary" onclick="GotoNext('orderStep')"> Next >> </button>
                        </div>

                    </div>
                    <div class="tab-pane container fade" id="orderStep">


                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" asp-for="SendSMS" id="flexCheckDefault">
                            <label class="form-check-label" for="flexCheckDefault">
                                Send SMS ?
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" asp-for="SendEmail" id="flexCheckChecked"
                                checked>
                            <label class="form-check-label" for="flexCheckChecked">
                                Send Email ?
                            </label>
                        </div>

                        <div class="form-check">
                            <input id="licenceAggrement" class="form-check-input" type="checkbox"
                                asp-for="AcceptAggrement" onchange="ReadAggrement()" id="flexCheckChecked">
                            <label class="form-check-label" for="flexCheckChecked">
                                Licence Aggrement ?
                            </label>
                        </div>


                        <div class="row  float-right mr-2">
                            <button class="btn btn-secondary" onclick="GotoPrev('creditStep')"> Prev << </button>
                                    &nbsp;
                                    <input disabled id="btnDoOrder" type="submit" class="btn btn-success"
                                        value="Sipariş Ver">
                        </div>

                    </div>
                </div>



            </form>
        </div>

        <div class="col-4">
            <vc:cart-detail></vc:cart-detail>
        </div>
    </div>



</div>




<button style="visibility: hidden;" id="btnOpenAggrement" type="button" class="btn btn-primary" data-toggle="modal"
    data-target="#licenceAggrementModal">
    Open modal
</button>

<!-- The Modal -->
<div class="modal" id="licenceAggrementModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Lisans Sözleşmesi</h4>
                <button id="btnClose" type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Lisans sözleşmesini okudum ve onaylıyorum.
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button id="btnCancel" type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                <button id="btnAggree" type="button" class="btn btn-primary" data-dismiss="modal">Aggree</button>
            </div>

        </div>
    </div>
</div>


@section Scripts {


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js" type="text/javascript"></script>

<script>
    $(document).ready(function () {
        DoMaskInput();
    })


    function DoMaskInput() {

        $('#phoneNumber').mask('(0)-000-000-00-00');
        $('#creditNumber').mask('0000-0000-0000-0000', { reverse: true });
        $('#validThru').mask('00/00');
        $('#cvv').mask('000');
    }




    function GotoNext(nextStepId) {
        event.preventDefault();

        $(`a[href="#${nextStepId}"]`).trigger('click');
    }

    function GotoPrev(prevStepId) {
        event.preventDefault();
        $(`a[href="#${prevStepId}"]`).trigger('click');
    }


    function ReadAggrement() {

        const currentState = $('#licenceAggrement').prop('checked'); // true yada false olarak döner.# // prop bize disabled yada checked gibi değerlerin değişimi veriyor.

        console.log('ReadAggrement', currentState);

        if (currentState) {
            console.log('btn', $("#btnOpenAggrement"));
            $('#btnOpenAggrement').trigger('click'); // modali aç
        }
        else {
            $('#btnDoOrder').prop('disabled', true); // sipariş butonunu kullanıma kapat
        }

    }


    $('#btnClose').click(function () {
        $('#licenceAggrement').prop('checked', false); // true olarak seçilen sözleşme kabul edilmediyse false çek
        $('#btnDoOrder').prop('disabled', true);

    })


    $('#btnAggree').click(function () {
        $('#btnDoOrder').prop('disabled', false);

    })

    $('#btnCancel').click(function () {
        $('#licenceAggrement').prop('checked', false); // true olarak seçilen sözleşme kabul edilmediyse false çek
        $('#btnDoOrder').prop('disabled', true);

    })



</script>
}