TestMVCApp/Controllers/OrderController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TestMVCApp.libs.Application;
using TestMVCApp.libs.Data.Contexts;
using TestMVCApp.libs.Data.Repositories;
using TestMVCApp.libs.Domain;
using TestMVCApp.Models;

namespace TestMVCApp.Controllers
{


    // uygulama içerisindeki bir durumun saklama şekillerine biz state management ismini durum yönetimiş ismini vberiyor

    // State Management 2 ye ayrılır

    // 1. ServerSide => Session, Application, Cache => Sunucu yani deploy çıktımızı Hosting makinadaki çözümler
    // 2. ClientSide => QueryString, Hidden Input, Cookie, WebStorage vs.. Tarayıcı tarafındaki çözümler

    // QueryString => sayfalar araası veri taşıma işlemlerinde, sayfada bir search sonucu bir kayıt araması yaparken tercih edilir.

    // Örnek => www.sanalticaret.com/ürünler?marka=adidas&beden=42
    // marka ve beden => key iken
    // adidas ve 42 değerleri ise value dur.

    // Hidden Input => bazen form bilgilerini suncuuya gönderirken bazı alanları input type="hidden" ile son kullanıcıya göstermeden göndermemiz gerekebilir. mesela edit yaparken id alanın bir önceki dersimizde hidden input ile httpost methoduna taşımıştık.

    // Cookie => Kullanıcı Login olduktan sonraki kullanıcı adı ve Profil fotoğrafı gibi bilgileri her istek de sunucundan tekrar tekrar sorgulamak bir maliyet ve performans kaybıdır. bu sebep ile bu tarz bilgiler key value formatında string olarak cookie de saklanır. tarayıcnın veri saklamak için kullandığı bir alandır. Maksimum 4kb veri saklanabilir. Cookie deki bilgiler, suncuya istek altığında gerekirse HttpRequest içerisinden otomatik olarak taşınır. Hassas bilgiler için güvenli bir veri taşıma yöntemi değildir. Javascript ile cookie bilgisi okunarak ekranda bir şeyler gösterilebilir. 

    // Web Storage yönteminde ise cookieden farklı olarak tarayıcıdaki storage alanında session yani oturum bazlı yada persist yani kalıcı olarak key value cinsinden veri saklayabiliriz. Her bir httpRequest de bu veriler tarayıcıdan sunucuya taşınmaz. Bu sebep ile cookieden farklı olup daha güvenli bir yöntemdir. (LocalStorage, SessionStorage) 2 adet storage tekniğini tarayıcılar destekler. Javascript ile bu verileri manüpüle edebiliyoruz.

    // Server Side statelerimiz ise Session => Client tarayıcıyı açıp ilgili domain adresine bir web request de bulunduğu an sunucu tarafında bu web request için tanımlanmış unique bir id'dir. biz buna sunucu tarafında session diyoruz. Bu unique id client tarayıcı kapatmayana kadar sunucu tarafında değişmez. Ne zaman tarayıcıyı kapatır yada (gizli sekmeden) bir tab açarız bu durumda sunucu tarafında yeni bir sessionıd oluşur. Session Id oturum bazlı en güvenilir veri tutma yönetmidir. çünkü session daki bilgiler web request içerinde saklanmaz sunucu tarafında tutulur. Session hacklenmesi için sessionId değerinin client a taşınması gerekir ki, hacker server'a eriştikten sonra ilgili sessionId üzerinden sunucudaki session ait bilgileri çalsın. Sepet gibi hassas bilgiler, kart bilgileri vs session üzerinde tutulabilir. Yada oturum açan kullanıcıya ait özlük bilgileri her seferinde db den çekilmek yerine sessionda saklanabilir.

    // Application ise => Uygulama bazlı sunucu tarafında veri tutmamızı sağlayan bir yöntemdir. Application ile sitemizi ziyaret eden aktif kullanıcı sayısı, uygulama ile alaklı ayarlar (mail atmak için gerekli olan konfigürasyon bilgileri) vb durumlar için tercih edilir. Oturum ve kullanıcı bazlı herhangi bir bilgi saklamak doğru değildir. Bu web sayfamızın gün içerisinde kaç web request aldığını filan bulabiliriz. 



    // Cache => Yani verilerin sürekli veri kaynağından çekmek yerine bir başka kaynak belli bir süre tutulup, buradan daha hızlı okunması işlemi. Genelde gün içerisinde çok fazla değişim göstemeyecek, günde 1 kez güncellenen veri operasyonları için tercih edilen bir yöntemdir. 
    // Veri tabanındaki ürün kategorileri, web uygulamamıza ait menüler, web sitemize ait renk temaları ve renk kodları, uygulamaya ait bazı konfigürasyon değerleri vs cache üzerinden okunabilir. Cacheden okunan değerler bir sunucunun raminde belli bir müddet tutulduğu için diskten yani hardiskten yada bir databaseden okumadan çok daha performanslıdır. 


    // EF Core Identity Service => CookieAuthentication (FormsAuthentication) => Web Project tercihi
    // Api TokenBasedAuthentication => Access Token erişim bileti ile kimlik dpoğrulama
    // Windows => LDAP Windows Autentication => PC hesabı ile kimlik doğrulama
    // School and Coperation Account ile Authentication => sadece şirket kimlik doğrulama

    // External Authentication => FB, Twitter, Google vs üzerinden kimlik doğrulama

    // EF Core Identity ile yukarıdaki tüm kimilk dopğrulama yöntemlerini kullanabiliyoruz. bunun için hazır yapılar var ve hazır tablolar var









    public class OrderController : Controller
    {

        private ICartService _cartService;
        private IOrderService _orderService;

        private ICustomerRepository _custormerRepo;

        private readonly UserManager<IdentityUser> _userManager;

        public OrderController(
        ICartService cartService,
        IOrderService orderService,
        UserManager<IdentityUser> userManager,
        ICustomerRepository customerRepo

        )
        {


            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
            _custormerRepo = customerRepo;
        }

        // Product/Save
        // Sepeti tamamlama işleminde yada satın alma işleminde OrderService ile çalışmamız lazım.

        // JsonResult ile sayfa yenilenmeden AJAx ile data işlemleri yapabiliriz. Sepete ekleme işleminde sayfa yenilenmeden bu işlemi yapmış olduk


        [HttpGet]
        public async Task<ActionResult> DoOrder()
        {

            // sipariş formu açılısında kullanıcı oturum açmış ise bu durumda şuan oturum açan müşteri bilgilerini getir.
            if (User.Identity.IsAuthenticated)
            {
                var authenticatedUser = await _userManager.FindByNameAsync(User.Identity.Name);

                var customer = _custormerRepo.Find(authenticatedUser.Id);

                var model = new OrderInputModel();
                model.CustomerDetail = new CustomerDetailModel
                {
                    FullName = customer.FullName,
                    ShipAddress = customer.DefaultShippingAddress,
                    CustomerId = customer.Id,
                    PhoneNumber = customer.PhoneNumber
                };


                return View(model);

            }


            return View();
        }


        [HttpPost]
        public ActionResult DoOrder(OrderInputModel model)
        {
            // 1 sipariş düzgün bir şekilde oluşur ise bu bilgileri database gönderip siparişe çevireceğiz ve 
            // daha sonrasında kullanıcıya bir mesaj verip sms email filan göndereceğiz.

            // Kredi kartı işlem enum
            // Başarılı 200
            // red 300
            // Limit Yertersiz 500 gibi
            // eğer Başarılı ise Sipariş oluşturma işlemini yapıp kullanıcıya sipariş kodunu dönelim.


            // 2 kredi kartı doğrulmasını yalancıktan yapalım eğer limit yeterli ise ve red verilmediyse sipariş oluşsun ve kullanıcıya ViewBag ile sipariş kodunu göster


            if (ModelState.IsValid)
            {

                var cart = _cartService.GetCart();
                _orderService.DoOrder(cart, model);

                ViewBag.OrderCode = _orderService.orderCode;
                ViewBag.OrderStatus = _orderService.Status;

                return View();

            }


            ViewBag.OrderCode = string.Empty;
            ViewBag.OrderStatus = string.Empty;




            return View();
        }


    }
}

TestMVCApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using TestMVCApp.libs.Application;
using TestMVCApp.libs.Data.Contexts;
using TestMVCApp.libs.Data.Entities;
using TestMVCApp.libs.Data.Repositories;
using TestMVCApp.Models;

namespace TestMVCApp.Controllers
{

    // dotnet new mvc --name=TestMVC --no-https => mvc proje açma komut
    // dotnet new web --name=TestRazorApp --no-https =>  razorpages proje açma komut


    // MVC LifeCyle
    // ilk istek controller a düşer
    // sonrasında ekranda yani view de (html,js,css olduğu sayfada) ekranda gösterilecek olan dinamik veriler (model) ile sayfalarımızı oluştururuz.

    // Home/Index
    // Home/Privacy
    // Home/Error
    // Controller/Action/Id

    public class ProductController : Controller
    {
        private readonly IProductRepository _repo;
        private readonly ICartService _cartService;

        public ProductController(IProductRepository repo, ICartService cartService)
        {
            _repo = repo;
            _cartService = cartService;
        }


        public IActionResult List()
        {
             var plist = _repo.toList();
             var cart = _cartService.GetCart();

            var model  = new ProductListVM(plist,cart);



            // var p1 = new Product();
            // p1.Name = "Ürün 1";
            // p1.ListPrice = 100;
            // p1.UnitPrice = 85;
            // p1.Stock = 10;

            // _repo.Create(p1);



            // var p2 = new Product();
            // p2.Name = "Ürün 2";
            // p2.ListPrice = 101;
            // p2.UnitPrice = 81;
            // p2.Stock = 20;

            // _repo.Create(p2);


            // var p3 = new Product();
            // p3.Name = "Ürün 3";
            // p3.ListPrice = 145;
            // p3.UnitPrice = 23;
            // p3.Stock = 30;

            // _repo.Create(p3);


            // var p4 = new Product();
            // p4.Name = "Ürün 4";
            // p4.ListPrice = 105;
            // p4.UnitPrice = 23;
            // p4.Stock = 21;

            // _repo.Create(p4);


            // var p5 = new Product();
            // p5.Name = "Ürün 5";
            // p5.ListPrice = 75;
            // p5.UnitPrice = 23;
            // p5.Stock = 21;

            // _repo.Create(p5);




           

            return View(model);
        }





    }
}

TestMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestMVCApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product"
                                asp-action="List">Ürünler</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order"
                                asp-action="DoOrder">Sipariş Ver</a>
                        </li>

                        @if(User.Identity.IsAuthenticated) {

                            <li class="nav-item">
                                <a class="nav-link text-dark">@User.Identity.Name</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="LogOut">Çıkış Yap</a>
                            </li>
                        }
                        else {
                              <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                    asp-action="Login">Oturum Aç</a>
                            </li>
                        }

                        
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>